version: "4.1.2"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

x-database-varibles: &database-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: postgres


services:
    website:
      image: debianbullseye-slim_production
      command: python manage.py runserver 0.0.0.0:8000
      volumes: *service-volumes
      environment: *app-variables
      depends_on:
        - db_migrate
      ports:
        - "8000:8000"
        -
    db_migrate:
      image: debianbullseye-slim_production
      command: python manage.py migrate
      volumes: *service-volumes
      environment: *app-variables

    postgres:
      image: postgres
      ports:
        - "8013:8013"
      environment: *database-variables
